// <auto-generated />
using System;
using HouseFinances.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HouseFinances.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HouseFinances.Domain.Entities.Category", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(400)
                    .HasColumnType("character varying(400)");

                b.Property<int>("Purpose")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.ToTable("Categories");
            });

            modelBuilder.Entity("HouseFinances.Domain.Entities.Person", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int>("Age")
                    .HasColumnType("integer");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.HasKey("Id");

                b.ToTable("Persons");
            });

            modelBuilder.Entity("HouseFinances.Domain.Entities.Transaction", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<decimal>("Amount")
                    .HasColumnType("numeric");

                b.Property<Guid>("CategoryId")
                    .HasColumnType("uuid");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(400)
                    .HasColumnType("character varying(400)");

                b.Property<Guid>("PersonId")
                    .HasColumnType("uuid");

                b.Property<int>("Type")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("CategoryId");

                b.HasIndex("PersonId");

                b.ToTable("Transactions");
            });

            modelBuilder.Entity("HouseFinances.Domain.Entities.Transaction", b =>
            {
                b.HasOne("HouseFinances.Domain.Entities.Category", "Category")
                    .WithMany("Transactions")
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("HouseFinances.Domain.Entities.Person", "Person")
                    .WithMany("Transactions")
                    .HasForeignKey("PersonId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Category");

                b.Navigation("Person");
            });

            modelBuilder.Entity("HouseFinances.Domain.Entities.Category", b =>
            {
                b.Navigation("Transactions");
            });

            modelBuilder.Entity("HouseFinances.Domain.Entities.Person", b =>
            {
                b.Navigation("Transactions");
            });
#pragma warning restore 612, 618
        }
    }
}
